services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Eskimo@910
      POSTGRES_USER: postgres
      POSTGRES_DB: gtcc-quiz
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
